### PR TITLE
jQuery fn usage instead of "new" 

### PR DESCRIPTION
**Pull request by dotansimha**
- Avoid using "new" and assume that "FlipClock" is available on "window" object.
- Use strict DI of Angular.

### CODE REVIEW

**Comment by stevermeister** [comment]
nice, thank you for the contribution!

**Comment by krish-ram** [comment]
looks like the fiddle doesn't work after the update..

**Comment by stevermeister** [comment]
hm, probably I was too careless with merging...

@krish-ram , thank you very much for pointing out!

**Comment by stevermeister** [comment]
@dotansimha,
sorry, it was problem with jsfiddle.
the code works fine. 

anyway I updated the version. Thank you all for contribution.

**Pull request merged**
